version: '3.1'

services:
  db:
    image: mariadb:lts-jammy
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: lia-planning

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080